int main(void)
void print_alphabet(void)
int add(int one, int two)
void print_times_table(int n)
int main(void)
int main(void)
int main(void)
int main(void)
void print_to_98(int n)
void print_alphabet_x10(void)
int _islower(int c)
int _isalpha(int c)
int print_sign(int n)
int _abs(int ab)
int print_last_digit(int nld)
void jack_bauer(void)
void times_table(void)
